def grade_quiz(quiz: list, student_answers: list) -> dict:
    """Compare student answers against the quiz answer key.

    Args:
        quiz: List of quiz questions generated by the Quiz Generation Skill.
        student_answers: List of answers selected by the student.

    Returns:
        - score (percentage of questions answered correctly)
        - correct (number of questions answered correctly)
        - total (total number of questions)
    """

    correct = 0
    total = len(quiz)

    missed_questions = []

    for i, (question, student_answer) in enumerate(zip(quiz, student_answers), start = 1):

        if student_answer.strip().upper() == question["answer"].strip().upper():
            correct += 1
        else:
            missed_questions.append({
                "question_number": i,
                "question": question["question"],
                "correct_answer": question["answer"],
                "student_answer": student_answer
            })


    score = round((correct / total) * 100, 2)

    return {"score": score, "correct": correct, "total": total, "missed_questions": missed_questions}
        
